# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

stages:
- stage: TF_DEPLOY
  jobs:
  - job:
    steps:
    - task: TerraformInstaller@1
      displayName: TF_INSTALL      
      inputs: 
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      displayName: TF_INIT
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'SPN-Project09'
        backendAzureRmResourceGroupName: 'S1-RG-CORE'
        backendAzureRmStorageAccountName: 'storagecrproject09564209'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'main.tf'
    - task: TerraformTaskV4@4
      displayName: TF_PLAN
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-out=main.tfplan -var-file=variables-dev.tfvars'
        environmentServiceNameAzureRM: 'SPN-Project09'
    - task: TerraformTaskV4@4
      displayName: TF_DEPLOY
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: 'main.tfplan'
        environmentServiceNameAzureRM: 'SPN-Project09'
        
- stage: TF_DECOMMISSION
  jobs:
  - job: ApproveDecom
    pool: server
    steps:
    - task: ManualValidation@0
      displayName: TF_Approve
      inputs:
        instructions: 'Stage TF_DECOMMISSION, do you approve?'
  - job: 
    dependsOn: ApproveDecom
    condition: Succeeded()
    steps:
    - task: TerraformInstaller@0
      displayName: TF_Destroy
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV3@3
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'SPN-Project09'
        backendAzureRmResourceGroupName: 'S1-RG-CORE'
        backendAzureRmStorageAccountName: 'storagecrproject09564209'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'main.tfstate'
    - task: TerraformTaskV3@3
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        environmentServiceNameAzureRM: 'SPN-Project09'