# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

stages:
- stage: TF_DEPLOY
  jobs:
  - job:
    steps:
    - task: TerraformInstaller@1
      displayName: TF_INSTALL      
      inputs: 
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      displayName: TF_INIT
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'SPN-Project09'
        backendAzureRmResourceGroupName: 'S1-RG-CORE'
        backendAzureRmStorageAccountName: 'storagecrproject09564209'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'main.tf'
    - task: TerraformTaskV4@4
      displayName: TF_PLAN
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'SPN-Project09'