# Starter pipeline: azure-pipelines-deploy.yml

pool:
  vmImage: ubuntu-latest

stages:
- stage: TF_DEPLOY
  jobs:
  - job:
    steps:
    - task: TerraformInstaller@1
      displayName: TF_INSTALL      
      inputs: 
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      displayName: TF_INIT
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'SPN-Project09'
        backendAzureRmResourceGroupName: 'S1-RG-CORE'
        backendAzureRmStorageAccountName: 'storagecrproject09564209'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'main.tfstate'
    - task: TerraformTaskV4@4
      displayName: TF_PLAN
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-out=main.tfplan -var-file=variables-dev.tfvars'
        environmentServiceNameAzureRM: 'SPN-Project09'
    - task: TerraformTaskV4@4
      displayName: TF_DEPLOY
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: 'main.tfplan'
        environmentServiceNameAzureRM: 'SPN-Project09'
        
